-- MySQL Script generated by MySQL Workbench
-- Mon May 14 12:33:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema relationships
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `relationships` ;

-- -----------------------------------------------------
-- Schema relationships
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `relationships` DEFAULT CHARACTER SET utf8 ;
USE `relationships` ;

-- -----------------------------------------------------
-- Table `relationships`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relationships`.`person` ;

CREATE TABLE IF NOT EXISTS `relationships`.`person` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL,
  `last_name` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `relationships`.`license`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `relationships`.`license` ;

CREATE TABLE IF NOT EXISTS `relationships`.`license` (
  `id` INT NOT NULL,
  `number` INT(8) ZEROFILL NOT NULL AUTO_INCREMENT,
--   `number` VARCHAR(255) NULL,
  `expiration_date` DATETIME NULL,
  `state` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `person_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  KEY(`number`),
  INDEX `fk_license_person_idx` (`person_id` ASC),
  CONSTRAINT `fk_license_person`
    FOREIGN KEY (`person_id`)
    REFERENCES `relationships`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
